### ISSUE TITLE
[Help] How can I show debug messages?

### ISSUE THREAD

**Issue by timdevorg** [CapsCollective/vulkan-cpp-starter#5]
Hello contributers,
I am pretty new to c++ and makefiles so I don't know how to enable this, so I'd like to ask for help on this type of topic.
How can I show debug messages eg. the supported list of extensions (seen here on the vulkan tutorial page: https://vulkan-tutorial.com/Development_environment#page_Setting-up-Visual-Studio just at the end of the Visual Studio setup)?
I would appreciate the help a lot!

**Comment by Raelr** [comment]
Hey @Proton64, 

Thank you so much for opening up this issue! Glad to see another more people are using this template! 

In terms of your issue - I've been researching this issue for a bit now. It seems that Windows makes life quite difficult for anyone who tries to develop C++ without Visual Studio. Luckily, there is a way to show debug messages and it can be done with only a few extra lines of code!

What you'll need to do is include `windows.h` in your `main.cpp` file and then add the following to the top of your `main` function:

```c++
#include <windows.h>

main() {
    AttachConsole(ATTACH_PARENT_PROCESS);\
    freopen("CON", "w", stdout);\
    freopen("CON", "w", stderr);\
    freopen("CON", "r", stdin);
}
```

What this does is re-route all debug messages to the parent process that ran the application. As such, if you were to run the process from Visual Studio Code, for example, the messages would appear in the Visual Studio Code terminal. This should apply to any IDE you choose to use as well. 

If you'd like to see an example of how this could be implemented, please refer to the implementation in one of my implementation's [`main.cpp` files](https://github.com/Raelr/vk-sandbox/blob/feature/transforms/src/main.cpp#L12-L19). In this example, I've wrapped the functionality in a macro called `WINDOWS_ATTACH_CONSOLE`. I then call the macro in the actual main function at line [118](https://github.com/Raelr/vk-sandbox/blob/feature/transforms/src/main.cpp#L118). 

I hope this is helpful! Please let me know if this helps solve your issue, I'm still looking into what the best method is for setting this up, but this seems to be the best method I've found so far.

**Comment by timdevorg** [comment]
Hey @Raelr 

Thank you for the quick response!

I added the lines and included the new header file and I can now see debug messages, eg. the list of supported extensions!
Thank you so much for helping me out, I am glad that I won't be having to rely on Visual Studio just because I want to develop Vulkan applications.

Cheers,
Tim.

**Comment by Raelr** [comment]
Thank you @Proton64! Glad to hear my suggestion helped. Good luck with your Vulkan adventures, looking forward to seeing what you can make!
